vesoft-inc/nebula-java

client/src/main/java/com/vesoft/nebula/meta/MetaExample.java, client/src/main/java/com/vesoft/nebula/meta/client/MetaClient.java, client/src/main/java/com/vesoft/nebula/meta/client/MetaClientImpl.java
Implemented meta client including init, getPart, getTagId, getEdgeType.
=> Implemented meta client

client/src/main/java/com/vesoft/nebula/Client.java, client/src/main/java/com/vesoft/nebula/meta/client/MetaClientImpl.java, client/src/main/java/com/vesoft/nebula/storage/client/StorageClient.java, client/src/main/java/com/vesoft/nebula/storage/client/StorageClientImpl.java, client/src/main/java/com/vesoft/nebula/utils/IPv4IntTransformer.java, examples/src/main/java/com/vesoft/nebula/examples/StorageClientExample.java
TODO: 
1. batch put/get/remove still have bugs.
2. PartId may be different from c++ implement, need to fix, I have not find a good solution...
=> remove part from storage client interface

client/pom.xml
=> Support maven gpg plugin in client module

README.md, client/pom.xml
=> Update release link

client/pom.xml, client/src/main/java/com/vesoft/nebula/Cluster.java, client/src/main/java/com/vesoft/nebula/graph/client/GraphClientImpl.java, client/src/main/java/com/vesoft/nebula/meta/client/MetaClient.java, client/src/main/java/com/vesoft/nebula/meta/client/MetaClientImpl.java, client/src/main/java/com/vesoft/nebula/utils/NebulaTypeUtil.java
=> Support show schemas

client/src/main/java/com/vesoft/nebula/client/graph/ResultSet.java
Names of columns offen are repeat, use String.intern() can save memory
=> Use Flyweight Pattern

client/src/main/java/com/vesoft/nebula/client/graph/ResultSet.java
=> fix NullPointerException #91

client/src/main/java/com/vesoft/nebula/client/graph/GraphClientImpl.java
=> do client signout before the TTransport is closed

client/src/main/java/com/vesoft/nebula/AbstractClient.java, client/src/main/java/com/vesoft/nebula/AsyncAbstractClient.java, client/src/main/java/com/vesoft/nebula/Client.java, client/src/main/java/com/vesoft/nebula/client/graph/GraphClientImpl.java, client/src/main/java/com/vesoft/nebula/client/graph/ResultSet.java, client/src/main/java/com/vesoft/nebula/client/meta/MetaClientImpl.java
Support thread local and fix code format.
=> Support thread local

client/src/main/java/com/vesoft/nebula/client/graph/GraphClientImpl.java
=> fix execution retry

client/src/main/java/com/vesoft/nebula/client/graph/ResultSet.java
=> [Client] Support getTimestamp()

client/src/main/java/com/vesoft/nebula/client/graph/ResultSet.java
=> add resultset throw exception

tools/exchange/pom.xml, tools/exchange/src/main/resources/server_application.conf, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/Exchange.scala, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/config/Configs.scala, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/config/SourceConfigs.scala, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/reader/ServerBaseReader.scala, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/utils/NebulaUtils.scala
Import data from HBase to nebula, just configure the src/main/resources/application.conf.
=> Add HBase datasource for nebula exchange

tools/nebula-spark/src/main/scala/com/vesoft/nebula/tools/connector/NebulaOptions.scala, tools/nebula-spark/src/main/scala/com/vesoft/nebula/tools/connector/example/Main.scala, tools/nebula-spark/src/main/scala/com/vesoft/nebula/tools/connector/package.scala
support `*` regex. 
use `*` to read all columns for one tag or edge, eg:
```
spark.read
.nebula("127.0.0.1:45500", "space", "100")
.loadVertices("player", "*")
```
=> Add  * as return all columns 

doc/tools/exchange/about-exchange/ex-ug-terms.md, doc/tools/exchange/about-exchange/ex-ug-what-is-exchange.md, doc/tools/exchange/ex-ug-toc.md
- removed company name from docs
- removed trademark symbols from docs
=> removed company name from docs

tools/nebula-algorithm/pom.xml, tools/nebula-algorithm/src/main/resources/application.conf, tools/nebula-algorithm/src/main/scala/com/vesoft/nebula/tools/algorithm/Main.scala, tools/nebula-algorithm/src/main/scala/com/vesoft/nebula/tools/algorithm/config/AlgoConfig.scala, tools/nebula-algorithm/src/main/scala/com/vesoft/nebula/tools/algorithm/config/Configs.scala, tools/nebula-algorithm/src/main/scala/com/vesoft/nebula/tools/algorithm/config/NebulaConfig.scala, tools/nebula-algorithm/src/main/scala/com/vesoft/nebula/tools/algorithm/config/SparkConfig.scala, tools/nebula-algorithm/src/main/scala/com/vesoft/nebula/tools/algorithm/lib/LouvainAlgo.scala, tools/nebula-algorithm/src/main/scala/com/vesoft/nebula/tools/algorithm/lib/PageRankAlgo.scala, tools/nebula-algorithm/src/main/scala/com/vesoft/nebula/tools/algorithm/utils/NebulaUtil.scala, tools/nebula-algorithm/src/test/scala/com/vesoft/nebula/tools/algorithm/config/ConfigSuite.scala, tools/nebula-algorithm/src/test/scala/com/vesoft/nebula/tools/algorithm/lib/LouvainExample.scala, tools/nebula-algorithm/src/test/scala/com/vesoft/nebula/tools/algorithm/lib/PageRankExample.scala, tools/nebula-algorithm/src/test/scala/com/vesoft/nebula/tools/algorithm/utils/NebulaUtilSuite.scala, tools/pom.xml
=> add graphx algorithm

examples/src/main/scala/com/vesoft/nebula/connector/ConnectorReaderExample.scala, tools/nebula-spark/src/main/scala/com/vesoft/nebula/tools/connector/reader/NebulaEdgeIterator.scala, tools/nebula-spark/src/main/scala/com/vesoft/nebula/tools/connector/reader/NebulaVertexIterator.scala
=> fix issue #189 

tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/config/Configs.scala, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/config/SourceConfigs.scala, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/processor/EdgeProcessor.scala, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/processor/Processor.scala, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/processor/VerticesProcessor.scala, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/reader/ServerBaseReader.scala, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/utils/NebulaUtils.scala
[exchange] add datatype conversion according to tag/edge schema
=> support auto datatype conversion

tools/exchange/src/main/resources/application.conf, tools/exchange/src/main/resources/server_application.conf, tools/exchange/src/main/resources/stream_application.conf, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/config/Configs.scala, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/processor/EdgeProcessor.scala, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/processor/VerticesProcessor.scala, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/writer/ServerBaseWriter.scala, tools/exchange/src/main/test/scala/com/vesoft/nebula/tools/importer/test/mock/MockConfigs.scala
1. add meta address for property file
2. print log when batch insert failed
=> modify the configuration of address for exchange

doc/tools/exchange/parameter-reference/ex-ug-paras-nebulagraph.md, doc/tools/exchange/use-exchange/ex-ug-import-from-neo4j.md
update parameters according to #196
=> doc: updated parameters

tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/processor/EdgeProcessor.scala, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/processor/VerticesProcessor.scala
Allow edge source and target  have no policy configure when hdfs file importing.
=> support numeric String source and target for edge

client/pom.xml
relocate com.google.guava to avoid dependency conflict.
=> add shade-plugin for java-client

examples/src/main/java/org/apache/flink/FlinkDemo.java, examples/src/main/java/org/apache/flink/NebulaCatalogDemo.java, tools/nebula-flink/pom.xml, tools/nebula-flink/src/main/java/org.apache.flink/connector/nebula/catalog/AbstractNebulaCatalog.java, tools/nebula-flink/src/main/java/org.apache.flink/connector/nebula/catalog/NebulaCatalog.java, tools/nebula-flink/src/main/java/org.apache.flink/connector/nebula/catalog/factory/NebulaCatalogFactory.java, tools/nebula-flink/src/main/java/org.apache.flink/connector/nebula/catalog/factory/NebulaDynamicTableSource.java, tools/nebula-flink/src/main/java/org.apache.flink/connector/nebula/statement/EdgeExecutionOptions.java, tools/nebula-flink/src/main/java/org.apache.flink/connector/nebula/statement/VertexExecutionOptions.java, tools/nebula-flink/src/main/java/org.apache.flink/connector/nebula/table/NebulaDynamicTableFactory.java, tools/nebula-flink/src/main/java/org.apache.flink/connector/nebula/table/NebulaDynamicTableSink.java, tools/nebula-flink/src/main/java/org.apache.flink/connector/nebula/table/NebulaDynamicTableSource.java, tools/nebula-flink/src/main/java/org.apache.flink/connector/nebula/table/NebulaRowDataInputFormat.java, tools/nebula-flink/src/main/java/org.apache.flink/connector/nebula/utils/DataTypeEnum.java, tools/nebula-flink/src/main/java/org.apache.flink/connector/nebula/utils/NebulaCatalogUtils.java, tools/nebula-flink/src/main/java/org.apache.flink/connector/nebula/utils/NebulaConstant.java, tools/nebula-flink/src/main/java/org.apache.flink/graph/descriptors/NebulaCatalogDescriptor.java, tools/nebula-flink/src/main/java/org.apache.flink/graph/descriptors/NebulaCatalogValidator.java, tools/nebula-flink/src/test/java/org/apache/flink/connector/nebula/catalog/NebulaCatalogTest.java, tools/nebula-flink/src/test/java/org/apache/flink/connector/nebula/sink/AbstractNebulaOutPutFormatTest.java
support nebula schema operations in flink
=> add flink-connector catalog

tools/exchange/README.md, tools/nebula-algorithm/README.md, tools/nebula-flink/README.md, tools/nebula-spark/README.md
updated user guide links in the README files of Exchange, Nebula Spark Connector, Nebula Flink Connector, and nebula-algorithm
=> doc: updated user guide links

tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/processor/EdgeProcessor.scala, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/processor/Processor.scala, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/processor/VerticesProcessor.scala
support vertex or edge which has escape symbol
=> support  escape for exchange

tools/exchange/src/main/resources/application.conf, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/config/Configs.scala, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/config/SourceConfigs.scala, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/processor/Processor.scala, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/reader/FileBaseReader.scala
update commit user name
add config
=> merged some fix

client/src/main/java/com/vesoft/nebula/client/storage/StorageClient.java, client/src/main/java/com/vesoft/nebula/client/storage/StorageClientImpl.java
1. fix scan
2. remove redundant modifier
=> fix scan for multi replica space

README.md
improved readme to make all the java tools in the v1.0 branch more findable.
=> doc: updated readme of the master branch

tools/nebula-spark/src/main/scala/com/vesoft/nebula/tools/connector/reader/NebulaRelation.scala
fix spark connector columns order mistaken
#226
=> fix issue #226: spark connector columns order mistaken

tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/processor/EdgeProcessor.scala, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/processor/Processor.scala, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/processor/VerticesProcessor.scala, tools/exchange/src/main/scala/com/vesoft/nebula/tools/importer/utils/NebulaUtils.scala
1.  remove `StringEscapeUtils` for escape symbol, because it convert Chinese to Unicode. 
2.  deal with escape symbol using `replaceAll`
=> fix Chinese import

client/src/main/java/com/vesoft/nebula/client/graph/ResultSet.java, examples/src/main/java/com/vesoft/nebula/examples/async/AsyncGraphClientExample.java
1 hotfix query ResultSet is empty bug 
2 add examples detail
=> hotfix v1.0 query ResultSet is empty bug and add examples detail

client/pom.xml, client/src/main/java/com/vesoft/nebula/AbstractClient.java, client/src/main/java/com/vesoft/nebula/Cluster.java, client/src/main/java/com/vesoft/nebula/client/graph/GraphClientImpl.java, client/src/main/java/com/vesoft/nebula/client/graph/async/AsyncGraphClientImpl.java, client/src/main/java/com/vesoft/nebula/client/meta/MetaClientImpl.java, client/src/main/java/com/vesoft/nebula/client/storage/StorageClientImpl.java
update guava version.
update func getHostText-> getHost.
I tried locally and successed.
=> update guava 14->23

client/src/main/java/com/vesoft/nebula/client/graph/GraphClient.java, client/src/main/java/com/vesoft/nebula/client/graph/GraphClientImpl.java, client/src/main/java/com/vesoft/nebula/client/graph/NGQLException.java, client/src/main/java/com/vesoft/nebula/client/graph/ResultSet.java, client/src/main/java/com/vesoft/nebula/client/graph/async/AsyncGraphClientImpl.java, examples/src/main/java/com/vesoft/nebula/examples/GraphClientExample.java
=> Add error message to the returned execute result

client/src/main/java/com/vesoft/nebula/encoder/NebulaCodecImpl.java, client/src/test/java/com/vesoft/nebula/encoder/TestEncoder.java
- delete the version of vertex
- modify the format of ranking
- fix to get the partId 
close #259
=> Sync the format of vertex key and edge key

client/src/main/java/com/vesoft/nebula/client/meta/MetaManager.java
used tagItems and fillMetaInfo will be invoked everytime.
=> Fix bug: should be edgeItems for getEdge.

client/src/main/java/com/vesoft/nebula/client/graph/data/Node.java, client/src/test/java/com/vesoft/nebula/client/graph/data/TestData.java, client/src/test/java/com/vesoft/nebula/client/graph/data/TestDataFromServer.java
Change the name of get tagNames method.
The origin method of 'labels' is confuse!
=> change labels to tagNames

client/src/main/java/com/vesoft/nebula/client/graph/net/NebulaPool.java, client/src/main/java/com/vesoft/nebula/client/graph/net/Session.java, client/src/main/java/com/vesoft/nebula/client/graph/net/SyncConnection.java, client/src/test/java/com/vesoft/nebula/client/graph/net/TestSession.java
- fix reconnect failed when all connections are idle status
- add test
=> Fix reconnect failed when all connections are idle status

tools/exchange/pom.xml
old repo for neo4j-contrib is unaccessible.
=> update dependency repo

client/src/main/java/com/vesoft/nebula/client/storage/scan/ScanVertexResultIterator.java
fix java.util.IllegalFormatConversionException, when scanVertex return error
=> fix java.util.IllegalFormatConversionException

client/src/test/resources/docker-compose.yaml
=> Replace v2-nightly docker image with nightly tag

client/src/main/java/com/vesoft/nebula/client/graph/data/DurationWrapper.java, client/src/test/java/com/vesoft/nebula/client/graph/data/TestData.java
sync https://github.com/vesoft-inc/nebula/pull/3608
=> update duration toString

README.md
jdbc reference added in note of readme
=> jdbc note added

README.md, client/pom.xml, client/src/test/resources/docker-compose-casigned.yaml, client/src/test/resources/docker-compose-selfsigned.yaml, client/src/test/resources/docker-compose.yaml, examples/pom.xml, pom.xml
wait for nebula and console release
=> update version to 3.0.0

client/src/main/java/com/vesoft/nebula/client/graph/net/RoundRobinLoadBalancer.java
Reverts vesoft-inc/nebula-java#477
=> Revert "add log for failed ping"

client/src/main/java/com/vesoft/nebula/client/graph/NebulaSession.java, client/src/main/java/com/vesoft/nebula/client/graph/SessionPool.java, client/src/main/java/com/vesoft/nebula/client/graph/SessionPoolConfig.java, client/src/test/java/com/vesoft/nebula/client/graph/net/TestSessionPool.java
Thanks @BleakStone  for the valuable suggestions in pr https://github.com/vesoft-inc/nebula-java/pull/474
=> add session healthCheck time & use thread-safe state for session

README.md
https://github.com/vesoft-inc/nebula-java/issues/471
=> update version match

client/src/main/java/com/vesoft/nebula/client/graph/net/SessionsManager.java
close https://github.com/vesoft-inc/nebula-java/issues/467
=> fix the NebulaPool state for SessionWrapper

README.md, client/pom.xml, client/src/test/resources/docker-compose-casigned.yaml, client/src/test/resources/docker-compose-selfsigned.yaml, client/src/test/resources/docker-compose.yaml, examples/pom.xml, pom.xml
=> update version to 3.4.0

.github/workflows/release.yaml, .github/workflows/snapshot.yaml
gpg config name in github is changed, `GPG_PRIVATE_KEY` -> `JAVA_GPG_PRIVATE_KEY`
=> modify the gpg config name

client/src/main/java/com/vesoft/nebula/client/graph/SessionPool.java, client/src/main/java/com/vesoft/nebula/client/graph/SessionPoolConfig.java, client/src/test/java/com/vesoft/nebula/client/graph/data/TestDataFromServer.java, client/src/test/java/com/vesoft/nebula/client/graph/net/TestSessionPool.java
enhance the retry mechanism for sessionpool, retry even for dead graphd and dead storaged, the retry times and interval time between retrys can be controlled by users
=> enhance the retry mechanism for sessionpool

client/src/test/resources/docker-compose-casigned.yaml, client/src/test/resources/docker-compose-selfsigned.yaml, client/src/test/resources/docker-compose.yaml
depend on the release of NebulaGraph and console.
=> update nebula image version to 3.5.0

client/pom.xml
close https://github.com/vesoft-inc/nebula-java/issues/453
=> upgrate guava

client/src/main/java/com/vesoft/nebula/client/graph/SessionPool.java, client/src/main/java/com/vesoft/nebula/client/graph/SessionPoolConfig.java, examples/src/main/java/com/vesoft/nebula/examples/GraphSessionPoolExample.java
=> add config for get session from sessionPool & remove lock for session state

client/src/main/java/com/vesoft/nebula/client/storage/StorageClient.java, client/src/test/java/com/vesoft/nebula/client/storage/StorageClientTest.java
* add graph host, user, password config  for StoragedClient;
* auth with user and password to though graphd;
* query the grants for user and maintain the space/labels WriteList for StoragedClient.
=> add auth for StorageClient scan 

.github/workflows/release.yaml
=> test selfhosted action

.github/workflows/release.yaml
Reverts vesoft-inc/nebula-java#575
=> Revert "test selfhosted action"

client/src/main/fbthrift/com/facebook/thrift/transport/THttp2Client.java
=> fix okhttpclient response body leak bug
