client/src/main/java/com/vesoft/nebula/client/meta/MetaClientImpl.java

It is useless, and will return null. We should not expose it.

remove getLeader

---

client/src/main/java/com/vesoft/nebula/client/graph/async/AsyncGraphClientImpl.java
client/src/main/java/com/vesoft/nebula/entry/AbstractNebulaCallback.java
client/src/test/java/com/vesoft/nebula/client/graph/async/TestGraphAsyncClient.java

Recently we are using spark-writer to import data from hive to nebula. Some clients hang for ever randomly.
Seems that there's no timeout when using AsyncClient even though we passed a timeout arguments
When using AsyncClient, we need set timeout to GraphService.AsyncClient instead of TNonblockingSocket. TNonblockingSocket just swallow the timeout argument and do nothing
Besides, we need set _isReady_ to true once the rpc call finished in AbstractNebulaCallback

Async client timeout bug

---

client/src/main/java/com/vesoft/nebula/AbstractClient.java
client/src/main/java/com/vesoft/nebula/AsyncAbstractClient.java
client/src/main/java/com/vesoft/nebula/Client.java
client/src/main/java/com/vesoft/nebula/client/graph/GraphClientImpl.java
client/src/main/java/com/vesoft/nebula/client/meta/MetaClientImpl.java

Clean unused code for com.vesoft.nebula.Client
Add connection timeout for Clients. The default timeout for TSocket is 0, which will block client infinitely when server behave strangely

Client connection timeout

---

client/pom.xml

delete slf4j-log4j12 dependency to prevent multiple slf4j binding classes.

modify slf4j-log4j12 to optional dependency

---

client/src/main/java/com/vesoft/nebula/client/meta/MetaManager.java
client/src/main/java/com/vesoft/nebula/client/storage/StorageClient.java
client/src/test/java/com/vesoft/nebula/client/meta/TestMetaManager.java

If User just use StorageClient, don't use MetaManager, When close StorageClient, then meta client is leaked, and in general, user don't know to use `MetaManager.getMetaManager(address).close()` to release meta client.
In my opinion, because MetaManager is a single instance, it should be just used at StorageClient, should be moved to storage package. If not, it shouldn't be single instance.

On StorageClient close, should also release meta client.

---

client/src/main/java/com/vesoft/nebula/client/graph/net/SyncConnection.java

fix https://github.com/vesoft-inc/nebula-java/issues/399

release the transport when version verification failed

---

client/src/main/java/com/vesoft/nebula/client/graph/data/DurationWrapper.java
client/src/main/java/com/vesoft/nebula/client/graph/data/ValueWrapper.java
client/src/main/java/com/vesoft/nebula/client/storage/data/BaseTableRow.java
client/src/test/java/com/vesoft/nebula/client/graph/data/TestData.java
client/src/test/java/com/vesoft/nebula/client/graph/data/TestDataFromServer.java

close https://github.com/vesoft-inc/nebula-java/issues/381

update thrift & support duration data type

---

client/pom.xml
examples/pom.xml

close https://github.com/vesoft-inc/nebula-java/issues/421
use `test` scope for fastjson, then user cannot use it outside nebula client unless users import it by themselves.

remove fastjosn for package

---

client/pom.xml

remove log4j in client package, just use it in test.
If users want to print log info for client, they should import slf4j's implement framework (slf4j-log4j12 or slf4j-logback) by themselves in business code.

update slf4j-log4j12 dependency's scope to test

---

client/src/main/java/com/vesoft/nebula/encoder/NebulaCodec.java
client/src/main/java/com/vesoft/nebula/encoder/NebulaCodecImpl.java
client/src/test/java/com/vesoft/nebula/encoder/TestEncoder.java

depend on https://github.com/vesoft-inc/nebula/pull/3328

add vertexKey without tag for encoder & add test

---

client/src/main/java/com/vesoft/nebula/client/meta/AbstractMetaClient.java

close: https://github.com/vesoft-inc/nebula-algorithm/issues/42
This validation check only allowed IP format hosts, the domain name
should be supported on both thrift and HostAndPort.
This is blocking the nebula graph in K8s from using spark/java clients.
ref:
- https://github.com/google/guava/blob/master/guava/src/com/google/common/net/HostAndPort.java

Fix host validation to support domain name

---

client/src/main/java/com/vesoft/nebula/client/graph/NebulaPoolConfig.java
client/src/main/java/com/vesoft/nebula/client/graph/net/NebulaPool.java
client/src/main/java/com/vesoft/nebula/client/graph/net/RoundRobinLoadBalancer.java
client/src/test/java/com/vesoft/nebula/client/graph/net/TestConnectionPool.java

Prevent application crash on init time when less than all graphd servers are available.
In the current version of nebula-java, if any of the graphd servers mentioned in config, is not accessible, the app going to crash.

Prevent application crash on init time

---

client/src/main/java/com/vesoft/nebula/client/graph/net/Session.java
client/src/main/java/com/vesoft/nebula/client/graph/net/SessionWrapper.java
client/src/test/java/com/vesoft/nebula/client/graph/net/TestSessionsManager.java

close https://github.com/vesoft-inc/nebula-java/issues/487

expose sessionID and ping check

---

README.md

close https://github.com/vesoft-inc/nebula-java/issues/493

add example for SessionPool

---

client/src/main/java/com/vesoft/nebula/client/graph/net/NebulaPool.java

fix https://github.com/vesoft-inc/nebula-java/issues/401
related pr https://github.com/vesoft-inc/nebula-java/pull/400, thanks @vchangpengfei for proposing the issue and pr.

check the connection's status when borrow and return

---

client/src/main/java/com/vesoft/nebula/client/meta/MetaClient.java

fix https://github.com/vesoft-inc/nebula-java/issues/409
When the leader host in response is empty, then fresh the meta client with input addresses. When the leader host is not empty, just use the leader host to update the meta client.

fix the leader state for CANDIDATE meta role

---

client/src/main/java/com/vesoft/nebula/client/graph/net/SyncConnection.java
client/src/main/java/com/vesoft/nebula/client/meta/AbstractMetaClient.java
client/src/main/java/com/vesoft/nebula/client/meta/MetaClient.java
client/src/main/java/com/vesoft/nebula/client/storage/GraphStorageConnection.java

https://github.com/vesoft-inc/nebula/issues/5191
when server transfer a large dataframe, client will hang. Using header protocol can throw the exception but not hang.

replace the protocol with header protocol

---

client/src/main/java/com/vesoft/nebula/client/graph/net/Session.java
client/src/main/java/com/vesoft/nebula/util/ReflectUtil.java

> The original push request is #461
When executeWithParameter is called in session, 
we expect more type to be valid params not only boolean/float/int/string/map/list.
On the basis of the original support types, the support for pojo, collection and time has been expanded.
The pojo type uses reflection values to convert to Map
```mermaid
graph TB
S--value-->N
N--Y_NullType-->E
N--N-->L
L--Y-->XV
XV-->E
L--N-->CV
CV-->S
CV(Collect_for / Map_for / Date: unit item)
XV(Value.xxxVal)
L{is leaf type}
S(value2Nvalue)
N{value is null}
E(return nValue)
```

enhancement:support more type value as parameter in session.value2Nvalue

---

.mvn/wrapper/maven-wrapper.properties
mvnw
mvnw.cmd

close https://github.com/vesoft-inc/nebula-java/issues/512
Thanks @wdroste  for your contribution about mvnw, refer https://github.com/vesoft-inc/nebula-java/pull/486

use maven wrapper to release the dependency on maven

---

client/src/main/java/com/vesoft/nebula/client/graph/NebulaSession.java
client/src/main/java/com/vesoft/nebula/client/graph/SessionPool.java
client/src/test/java/com/vesoft/nebula/client/graph/data/TestDataFromServer.java
client/src/test/java/com/vesoft/nebula/client/graph/net/TestSessionPool.java

close https://github.com/vesoft-inc/nebula-java/issues/515

recreate session for both session error and connection exception

---

client/src/main/java/com/vesoft/nebula/client/graph/SessionPool.java
client/src/main/java/com/vesoft/nebula/client/graph/SessionPoolConfig.java

Isolation is config with SessionPoolConfig.setReconnect(),  the default value is false, meaning no reconnect with other available server hosts.
If reconnect is true, try all available server hosts util it connects succeed or hosts is exhausted.

isolate broken graphd server while client application is running

---

client/src/main/java/com/vesoft/nebula/client/graph/NebulaPoolConfig.java
client/src/main/java/com/vesoft/nebula/client/graph/SessionPool.java
client/src/main/java/com/vesoft/nebula/client/graph/SessionPoolConfig.java
client/src/main/java/com/vesoft/nebula/client/graph/net/ConnObjectPool.java
client/src/main/java/com/vesoft/nebula/client/graph/net/Connection.java
client/src/main/java/com/vesoft/nebula/client/graph/net/NebulaPool.java
client/src/main/java/com/vesoft/nebula/client/graph/net/RoundRobinLoadBalancer.java
client/src/main/java/com/vesoft/nebula/client/graph/net/SyncConnection.java

close https://github.com/vesoft-inc/nebula-java/issues/547

support to set headers for http2

---

README.md
examples/src/main/java/com/vesoft/nebula/examples/GraphSessionPoolExample.java
examples/src/main/java/com/vesoft/nebula/examples/GraphSessionPoolWithHttp2Example.java
examples/src/main/java/com/vesoft/nebula/examples/StorageClientExample.java

https://github.com/vesoft-inc/nebula-java/issues/550

fix log className and README.md code style

---

client/src/main/java/com/vesoft/nebula/client/graph/NebulaPoolConfig.java
client/src/main/java/com/vesoft/nebula/client/graph/SessionPool.java
client/src/main/java/com/vesoft/nebula/client/graph/SessionPoolConfig.java
client/src/main/java/com/vesoft/nebula/client/graph/net/ConnObjectPool.java
client/src/main/java/com/vesoft/nebula/client/graph/net/Connection.java
client/src/main/java/com/vesoft/nebula/client/graph/net/NebulaPool.java
client/src/main/java/com/vesoft/nebula/client/graph/net/RoundRobinLoadBalancer.java
client/src/main/java/com/vesoft/nebula/client/graph/net/SyncConnection.java
client/src/main/java/com/vesoft/nebula/client/meta/MetaClient.java
client/src/main/java/com/vesoft/nebula/client/meta/MetaManager.java
client/src/main/java/com/vesoft/nebula/client/storage/StorageClient.java
client/src/test/java/com/vesoft/nebula/client/graph/net/TestConnectionPool.java
client/src/test/java/com/vesoft/nebula/client/meta/TestMetaClient.java
client/src/test/java/com/vesoft/nebula/client/storage/StorageClientTest.java
client/src/test/resources/docker-compose.yaml
examples/src/main/java/com/vesoft/nebula/examples/GraphClientExample.java

close https://github.com/vesoft-inc/nebula-java/issues/567
close #568 
close #569 
the new config for `version` is optional, there is no confluence for old users.
For users who need to config a special version, the usage is:
NebulaPool:
```
NebulaPoolConfig nebulaPoolConfig = new NebulaPoolConfig();
nebulaPoolConfig.setVersion("test");
```
SessionPool:
```
SessionPoolConfig sessionPoolConfig =new SessionPoolConfig(addresses, spaceName, user, password)
.setVersion("test");
```
MetaClient:
```
MetaClient client = new MetaClient(address, port);
client.setVersion("test");
```
StorageClient:
```
StorageClient storageClient = new StorageClient(address);
storageClient.setVersion("test");
```

support to config the version white list

---

client/src/main/java/com/vesoft/nebula/client/graph/NebulaSession.java
client/src/main/java/com/vesoft/nebula/client/graph/SessionPool.java

add executeJsonWithParameter, executeJson to SessionPool

add executeJsonWithParameter, executeJson to SessionPool

---

client/src/main/java/com/vesoft/nebula/client/graph/NebulaPoolConfig.java
client/src/main/java/com/vesoft/nebula/client/graph/data/CASignedSSLParam.java
client/src/main/java/com/vesoft/nebula/client/graph/data/SSLParam.java
client/src/main/java/com/vesoft/nebula/client/graph/net/ConnObjectPool.java
client/src/main/java/com/vesoft/nebula/client/graph/net/RoundRobinLoadBalancer.java
client/src/main/java/com/vesoft/nebula/client/graph/net/SyncConnection.java
client/src/main/java/com/vesoft/nebula/util/SslUtil.java
examples/src/main/java/com/vesoft/nebula/examples/GraphSSLExample.java

support tls single authentication

---

client/src/main/fbthrift/com/facebook/thrift/transport/THttp2Client.java

close https://github.com/vesoft-inc/nebula-java/issues/599
复现场景：
* 并发20，每个并发内执行20次query。
* 执行完成后 进程退出前等待5分钟，便会出现日志“a connection to http:// was leadked. Did you forget to close a response body”。 
要等待5分钟才出现日志是因为okhttp client内有一个connection pool，pool的cleanup任务是默认5分钟执行一次。上述日志便是cleanup时发现 池子中的connection还在使用但引用者为空，便认定该connection 泄漏，于是会打印日志并将其清除。
解决：
重构http2Client中flush和read的方式，在flush时将response 的全部数据流取出给到一个全局buffer， read时 一批批的从全局buffer中读取。
测试：
* 并发20执行，进程等待5分钟后自动退出，无 日志出现。 
* 因为 client中定义的okhttpclient是个单例，且内部维护了okhttp的connection pool，为了确认在执行过程中调用http2Client.close 不影响已有session的执行，进行如下测试：（结果是 不影响已有session的执行）
* 临时修改代码逻辑：当创建sessionn时发生auth失败，统一做connection.close，不关sessionPool。
* 池子设置max是20，min是10.初始化的时候会建好10个链接。
* 跑一个单线程的查询，sleep10 秒。
* 中间手动把用户给删除。
* 跑 20并发每个并发20次操作的查询，有10次 user not exit的 …

fix okhttpclient response body leak bug

---

client/src/main/java/com/vesoft/nebula/client/meta/MetaClient.java
client/src/main/java/com/vesoft/nebula/client/meta/MetaManager.java
client/src/main/java/com/vesoft/nebula/client/storage/StorageClient.java
client/src/main/java/com/vesoft/nebula/util/NetUtil.java
examples/src/main/java/com/vesoft/nebula/examples/SpecialAddressStorageClientExample.java

When scanning with storageClient, the storage address obtained from meta may not be used directly, such as 127.0.0.1. The code executed must be used with the storage service, but often the business code and the nebula server are not on the same machine or the same network segment. This results in the inability to scan the data using storageClient
StorageClient initializes the Address translation relationship, and then MateManger returns address translation
Because of runing the local nebula-client exception, the code did not run the unit tests

Add storage address mapping transform
